### ISSUE TITLE
Tailwind production stylesheet not working with gmail

### ISSUE THREAD

**Issue by affanshahid** [shellscape/jsx-email#110]
- Component or Package Name: jsx-email (Tailwind component)
- Component or Package Version: 1.5.0
- `@jsxp-email/cli` Version?: 3.0.1
- Operating System (or Browser): macOS / Chrome
- Node Version: v19.8.1
- Link to reproduction _(⚠️ read below)_: https://stackblitz.com/edit/jsx-email-repro-hq7dz6?file=templates%2FReproduction.tsx

### Expected Behavior
When using the Tailwind component with the production prop the generated stylesheet should be compatible with gmail clients.

### Actual Behavior
The generated stylesheet is not compatible with gmail because some of the generated/hashed class names start with a number and so must be escaped. (eg. `.\35 91fxo  {...}`). Check the style tag in the HTML tab on the reproduction link.

### Additional Information
This can potentially be fixed by allowing a prefix to be supplied here: https://github.com/shellscape/jsx-email/blob/b13a38234a922ec591bddd6eec56a84ed00da73a/packages/jsx-email/src/components/tailwind/tailwind.tsx#L35

**Comment by shellscape** [comment]
Thanks for the issue and for triaging! Always appreciate that. It's a holiday weekend in the U.S. so I'll mostly be offline until tomorrow. Will get this looked at as soon as possible.

**Comment by affanshahid** [comment]
Happy holidays. Changing the prefix does indeed fix the issue for me, I can PR this but not sure how to best accept the prop.

Would a separate prop make sense?
```tsx
<Tailwind production classPrefix="foo" />
```

**Comment by shellscape** [comment]
A PR would be awesome. I think we can set a reasonable static value that isn't exposed by a prop for a fast fix. If there's user demand to change that prefix we can iterate and expose it as a configurable prop.

**Comment by lordelogos** [comment]
Thanks @affanshahid for the catch and fix👍🏽
