### ISSUE TITLE
key prop is missing on Select.Item component

### ISSUE THREAD

**Issue by Aboubakary833** [shellscape/jsx-email#123]
- Component or Package Name: preview
- Component or Package Version: 1.7.0
- `@jsxp-email/cli` Version?: 1.7.0
- Operating System (or Browser): PopOS/Chrome
- Node Version: 18.17.1
- Link to reproduction _(⚠️ read below)_: N/A

It seems that the `key` prop is missing on `Select.Item` component inside the preview [mobile.jsx](https://github.com/shellscape/jsx-email/blob/main/apps/preview/app/src/components/mobile.tsx) file, what generate the following error in my browser console:

![image](https://github.com/shellscape/jsx-email/assets/58236609/1cd91db6-7b5e-42f9-bde4-52b165ce7540)

**Comment by lordelogos** [comment]
Hey @Aboubakary833, 
Thank you for this catch.
Would you be interested in submitting a pull request for this fix?

**Comment by Aboubakary833** [comment]
Done
