### ISSUE TITLE
Previewer hang when using empty files and default arguments

### ISSUE THREAD

**Issue by Gobot1234** [shellscape/jsx-email#125]
- Component or Package Name: react
- Component or Package Version: 18.2
- `@jsxp-email/cli` Version?: v1.6.1
- Operating System (or Browser): macOS/Chromium
- Node Version: 21.5
- Link to reproduction:

https://stackblitz.com/edit/jsx-email-repro-fcbu37?file=templates/Reproduction.tsx

### Expected Behavior
The previewer should work
### Actual Behavior
The previewer never loads
### Additional Information
For the issue you need to move the footer.tsx file between test and templates. This seems to be interacting with default arguments weirdly because removing them makes everything work fine.

**Comment by Gobot1234** [comment]
Issue was resolved by using a different folder for the footer component and importing from their

**Comment by shellscape** [comment]
We're still going to add some code to protect against this 👍
