### ISSUE TITLE
Add `zod` and `yup` support for creating default props

### ISSUE THREAD

**Issue by shellscape** [shellscape/jsx-email#134]
As much as I loathe `zod`, this needs to be done.

This is a placeholder issue for a task for jsx-email v1.6.0

**Comment by CanRau** [comment]
Just in case throwing in here that I like (& use) [valibot](https://valibot.dev/) a lot.
Not sure how the current `TemplateStruct` works under the hood but probably a good idea to make it general so you can use whatever

**Comment by CanRau** [comment]
How would I currently use valibot, isn't it running superstructs create behind the scenes or did I get your comment wrong?

1 option could be keeping the current behavior but if `TemplateStruct` (maybe with a different name) is set to a function just run that with some context data so within that function people can do what they want, but would be more boilerplate and also type inference will be harder, maybe via a generic.

I'm on my phone right now 😅

**Comment by shellscape** [comment]
Have been playing with this idea a lot and the one thing that I've been struggling with is where the value is added - there's no real advantage to having builtin support for _any_ validator libraries. There's no real time savings for the user, and there's no real complexity savings either. If anything, it potentially makes the templates _more_ complex.

At the moment, we're going to remove the builtin superstruct support for the next major version, and table the idea for the meantime.
