### ISSUE TITLE
New Template Example: ring.com

### ISSUE THREAD

**Issue by shellscape** [shellscape/jsx-email#143]
This would be a great first contribution for someone. We'd like to add a new template to the `/apps/demo` app. This is a ring.com password reset email. 

Screenshot:

<img width="801" alt="Screenshot 2024-01-15 at 11 04 51 PM" src="https://github.com/shellscape/jsx-email/assets/76371/ffb91699-aac7-4c56-b530-4bf6e638f4a5">

HTML: https://gist.github.com/shellscape/5f3522d785ed2b971191108c5fd81f43

Note that while the template has a `font-size` of `38px` set in the `style` attribute, Gmail overrides this as `12.5px`

<img width="938" alt="Screenshot 2024-01-15 at 11 04 13 PM" src="https://github.com/shellscape/jsx-email/assets/76371/76788733-74a1-4cd6-a3e8-f16ba9cfd5ce">

**Comment by abdulsamadayoade** [comment]
@shellscape I'm interested in working on this

**Comment by shellscape** [comment]
awesome! please do, and let me know how I can help.
