### ISSUE TITLE
Optional flag to toggle browser auto-open when launching email preview

### ISSUE THREAD

**Issue by Crateros** [shellscape/jsx-email#166]
- Component or Package Name: N/A
- Component or Package Version: jsx-email-v1.10.8

### Expected Behavior / Situation
Attempting to run jsx-email in a Docker container. The email preview server attempts to automatically launch a browser tab for convenience, this obviously does not work inside of a Docker container.

![Screenshot 2024-02-01 at 11 02 29 AM](https://github.com/shellscape/jsx-email/assets/17658464/716776f2-f8a1-4572-8a1b-f186cbb55c35)

### Actual Behavior / Situation
N/A

### Modification Proposal
Add an optional flag to pass to the `email preview` command to toggle whether or not an attempt to open a browser tab is made.

**Comment by shellscape** [comment]
Hey there thanks for the issue. If you run `email preview --help` you'll see a list of options. The `--no-open` flag is what you're looking for.

**Comment by Crateros** [comment]
@shellscape Thank you! I referred to the docs but should have inspected the CLI help as well. This works 👍
