### ISSUE TITLE
 WARN  1 deprecated subdependencies found: source-map-resolve@0.6.0

### ISSUE THREAD

**Issue by deadcoder0904** [shellscape/jsx-email#168]
- Component or Package Name: source-map-resolve
- Component or Package Version: 0.6.0

### Expected Behavior / Situation

Shows this in the terminal every single time:

> WARN  1 deprecated subdependencies found: source-map-resolve@0.6.0

### Actual Behavior / Situation

Should not show it.

### Modification Proposal

Use https://github.com/adobe/css-tools (or https://www.npmjs.com/package/@adobe/css-tools) from https://github.com/reworkcss/css/issues/164 instead of https://github.com/reworkcss/css/

When I did `npm ls source-map-resolve` to see what dependency used it, I saw this:

> `-- jsx-email@1.10.9 -> .\node_modules\.pnpm\jsx-email@1.10.9_@jsx-email+app-preview@1.2.5_@types+node@20.11.16_@types+react@18.2.55_react@18.2.0\node_modules\jsx-email
  `-- @jsx-email/doiuse-email@1.0.1 -> .\node_modules\.pnpm\@jsx-email+doiuse-email@1.0.1\node_modules\@jsx-email\doiuse-email
    +-- css@3.0.0 -> .\node_modules\.pnpm\css@3.0.0\node_modules\css
    | `-- source-map-resolve@0.6.0 -> .\node_modules\.pnpm\source-map-resolve@0.6.0\node_modules\source-map-resolve
    `-- style-to-object@1.0.5 -> .\node_modules\.pnpm\style-to-object@1.0.5\node_modules\style-to-object
      `-- inline-style-parser@0.2.2 -> .\node_modules\.pnpm\inline-style-parser@0.2.2\node_modules\inline-style-parser
        `-- css@3.0.0 -> .\node_modules\.pnpm\css@3.0.0\node_modules\css
          `-- source-map-resolve@0.6.0 deduped -> .\node_modules\.pnpm\source-map-resolve@0.6.0\node_modules\source-map-resolve

Its just a simple warning in the terminal but really annoying to see everytime I install a new dependency.

**Comment by deadcoder0904** [comment]
Looks like someone else opened it first: https://github.com/shellscape/doiuse-email/issues/5

**Comment by deadcoder0904** [comment]
There's also an open PR: https://github.com/shellscape/doiuse-email/pull/6

Can you merge it & release a new version?

**Comment by shellscape** [comment]
Thanks for the issue. These warning is safe to ignore. You can hide them by changing the npm log level on the command line or in npmrc. This isn't actionable in this repo, so closing here
