### ISSUE TITLE
Email preview 

### ISSUE THREAD

**Issue by theDanielJLewis** [shellscape/jsx-email#181]
- Component or Package Name: @jsx-email
- Component or Package Version: 1.10.12
- `@jsxp-email/cli` Version?: v1.10.11
- Operating System (or Browser): Arc (Chrome based)
- Node Version: 21.6.2
- Link to reproduction _(⚠️ read below)_: (base JSX Email does this)

### Expected Behavior

I expect the email preview feature to offer a dropdown menu or another way to navigate among templates when the browser is not wide enough to display the sidebar.

### Actual Behavior

At the smaller breakpoints, the sidebar disappears and there's no way to navigate among email templates.

### Additional Information

Simply run `email preview` and shrink the width of your browser to see the problem.

**Comment by shellscape** [comment]
This is resolved by #182, which will be released on the next v2.0.0 preview next week. 

FWIW we have the mobile view in the preview so users don't have to resize the preview, but with the tagged PR, it should be possible to.
