### ISSUE TITLE
Website search bug template display 

### ISSUE THREAD

**Issue by Kampouse** [shellscape/jsx-email#185]
in the documentation there is  a bug while cetain trigger a display of template display rather than actual value 
### Expected Behavior
not show it 
### Actual Behavior
![image](https://github.com/shellscape/jsx-email/assets/41765025/c65b6213-02c7-4978-99c2-736a423c3e96)

### Additional Information
nice project

**Comment by shellscape** [comment]
Thanks for the issue. Unfortunately that's a vitepress bug. Not much we can do about that at the moment. Hopefully they fix it soon!

**Comment by shellscape** [comment]
We're going to be moving to Astro Starlight so this won't be an issue afterwards. Thanks again for reporting, closing for housekeeping.

**Comment by Kampouse** [comment]
great news!
