### ISSUE TITLE
Bun support

### ISSUE THREAD

**Issue by nephix** [shellscape/jsx-email#197]
- Component or Package Name: `jsx-email`
- Component or Package Version: `^1.12.1`
- `@jsxp-email/cli` Version?: idk
- Operating System (or Browser): macOS 14.5
- Bun Version: `1.1.12`
- Link to reproduction : https://github.com/nephix/jsx-email-repro

I'm not sure whether this is an issue in `bun`, `jsx-email` or `shikiji`, apologies

After `bun install`, when I run:

```
bun run index.ts
```

it works fine and prints the HTML content of the template

When running

```
bun run build
bun dist/index.js
```

### Expected Behavior

Rendered HTML content of template as output

### Actual Behavior

```
bun dist/index.js
71997 |       captureIndices
71998 |     };
71999 |   }
72000 | }
72001 |
72002 | class Registry2 extends Registry$1 {
        ^
TypeError: The superclass is not a constructor.
      at jsx-email-repro/dist/index.js:72002:1
note: missing sourcemaps for jsx-email-repro/dist/index.js
note: consider bundling with '--sourcemap' to get an unminified traces
```

### Additional Information

When I add `--sourcemap`:

```
bun dist/index.js

4739 |
 "&'/=>`'.split('')],
4740 |
 "&'/=>`'.split('')],
4741 |
 "&'/=>`'.split('')],
4742 |
 "&'/=>`'.split('')],
4743 |
 "&'/=>`'.split('')],
4744 |
 "&'/=>`'.split('')],
       ^
TypeError: The superclass is not a constructor.
      at jsx-email-repro/node_modules/shikiji-core/dist/index.mjs:4744:1
```

**Comment by shellscape** [comment]
thanks for the issue. unfortunately bun is not a priority at the moment before the project. that said if you'd like to contribute support for bun, we'd welcome it as long as it's not a destructive change.

**Comment by shellscape** [comment]
@Jarred-Sumner this looks like a bug within bun. that error should not be thrown, and is not in node

**Comment by shellscape** [comment]
Thanks again for reporting this. Going to close this as it's an issue with Bun upstream, and isn't something we can work around. Please feel free to ping me if you need backup on that bun issue, etc.
