### ISSUE TITLE
Light Mode

### ISSUE THREAD

**Issue by btxtiger** [shellscape/jsx-email#200]
- Component or Package Name: jsx-email
- Component or Package Version: 1.10.11

### Feature Use Case
I find it very frustrating, that the dev UI is only available in dark mode, which is very unusual for email environments. This gives a different feeling of how the mail would look like for most recipients.

### Feature Proposal
Add a light theme

**Comment by shellscape** [comment]
Thanks for the issue. Since this is a project maintained by devs, and we live on the contribution of devs, I'd like to suggestion contributing a light mode theme to the project that would suit your needs.

**Comment by shellscape** [comment]
Closing this as "not planned" because it's something that the current maintainers don't have planned. But we'd still welcome a contribution to add light mode to the preview and the docs!
