### ISSUE TITLE
"Attempted to assign to readonly property" error when compiled via Bun

### ISSUE THREAD

**Issue by EvHaus** [shellscape/jsx-email#202]
- Component or Package Name: `jsx-email`
- Component or Package Version: `1.12.1`
- `@jsxp-email/cli` Version?:  Not sure what this is
- Operating System (or Browser): MacOs
- Node Version: Bun 1.1.25
- Link to reproduction _(⚠️ read below)_: Requires very minimal code, see below

### Steps to reproduce

Seems like `jsx-email` cannot be bundled via `Bun` without errors. Take the following tiny example:

```js

// index.tsx

import { render } from 'jsx-email';
console.log(await render(<div>Hello World</div>));
```

This works just fine when executed via `bun index.tsx`. But if you attempt to compile it via:

```
bun build --compile index.tsx --outfile ./app --target bun
```

And then run the compiled service via:

```
./app
```

You end up with this error:

```
9731 |     CharCodes2[CharCodes2["LOWER_Z"] = 122] = "LOWER_Z";
9732 |     CharCodes2[CharCodes2["UPPER_A"] = 65] = "UPPER_A";
9733 |     CharCodes2[CharCodes2["UPPER_F"] = 70] = "UPPER_F";
9734 |     CharCodes2[CharCodes2["UPPER_Z"] = 90] = "UPPER_Z";
9735 |   })(CharCodes || (CharCodes = {}));
9736 |     BinTrieFlags2[BinTrieFlags2["VALUE_LENGTH"] = 49152] = "VALUE_LENGTH";
                                      ^
TypeError: Attempted to assign to readonly property.
      at /$bunfs/root/app:9736:32
      at /$bunfs/root/app:9739:5
      at /$bunfs/root/app:28:48
      at /$bunfs/root/app:90243:12
```

### Expected Behavior

Should be able to execute `jsx-email`'s `render()` method after compiling the code via Bun's compiler.

### Actual Behavior

Getting `Attempted to assign to readonly property.` error

### Additional Information

Seems like maybe this is dying somewhere in the `entities` code? Might be caused by https://github.com/fb55/htmlparser2/issues/1782

**Comment by EvHaus** [comment]
Closing. Most likely a bug with Bun's bundler.

**Comment by shellscape** [comment]
Right on..Happy to help where I can but not a bun user personally.
