### ISSUE TITLE
Loops API support

### ISSUE THREAD

**Issue by vixeven** [shellscape/jsx-email#203]
Documentation Is:

- [x] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain

In README.md ([Service Integration](https://jsx.email/docs/introduction#service-integrations)) it says that it supports [Loops](https://loops.so) API for sending emails. There is no Loops example in [Email Providers](https://jsx.email/docs/email-providers).

But in [Loops > Transactional email > Guide](https://loops.so/docs/transactional/guide) it says that transaction emails must be include `transactionalId` (email template create with-in Loops). There is no `html` property in the [API request](https://loops.so/docs/api-reference/send-transactional-email#body).

Also, from [Loops > Integrations > Supabase](https://loops.so/docs/integrations/supabase#configure-email-templates-in-supabase):
> Loops SMTP integrations work a bit differently than most. Instead of sending a text or HTML email body, you set them up to send API-like data.

Am I missing any details? Is `jsx-email` actually compatible with Loops?

**Comment by shellscape** [comment]
You can still use jsx-email to render your template to HTML, and that can be used to create the template in loops. That's what a company I work with presently does. So in that way, we're compatible with Loops.

_(And I've been asking https://x.com/frantzfries for raw html support for the better part of two years in Loops.)_

**Comment by shellscape** [comment]
I pinged Chris to see if anyone from Loops can pop in here to help. In the mean time we're going to close this for housekeeping. I'll make a note to add some docs on how one might use jsx-email with loops.
