### ISSUE TITLE
Document how to use context

### ISSUE THREAD

**Issue by sandinmyjoints** [shellscape/jsx-email#227]
- Component or Package Name: jsx-email
- Component or Package Version: 2.0.11

Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

I wanted to use context, and had to look at https://github.com/shellscape/jsx-email/pull/179 to realize I needed to `import { createContext, useContext } from 'jsx-email';` instead of from react. 

### Your Proposal for Changes

Mention that to use context, you must import these from jsx-email. Could go in the FAQ, or maybe there's a better place for it.

**Comment by shellscape** [comment]
Great suggestion. Would you be up for writing what you'd like to see in a PR?
