### ISSUE TITLE
can currently not be used in `tsx` scripts: `does not provide an export named ..`

### ISSUE THREAD

**Issue by boredland** [shellscape/jsx-email#24]
### Expected Behavior

Being able to import the render function.

I am using the latest version of `@jsx-email/render`. 

### Actual Behavior

```
import { render } from "@jsx-email/render";
--
09:04:15.584 | ^
09:04:15.584 |  
09:04:15.584 | SyntaxError: The requested module '@jsx-email/render' does not provide an export named 'render'

```

**Comment by shellscape** [comment]
I'm afraid you're going to have to provide more information. We're using the import exactly like that in a few places including https://github.com/shellscape/jsx-email/blob/9a4f4c9eda84d1cf113929f2bf1ba3f79c8af6ff/packages/cli/src/commands/build.ts#L6

**Comment by boredland** [comment]
> Cool let's keep this open for tracking. I suspect it's on their end at the moment.

Me too. For reading this due to similar issues: for me using `bunx` instead of `tsx` is a viable alternative without the hurdles.

**Comment by boredland** [comment]
Seems amending the initial issue was not appreciated, so I created a new one: https://github.com/esbuild-kit/tsx/issues/331

**Comment by boredland** [comment]
I currently can't reproduce this outside of my main codebase. Will re-open as soon as I can...
