### ISSUE TITLE
The preview build does not work when deployed on subpath

### ISSUE THREAD

**Issue by timofei-iatsenko** [shellscape/jsx-email#245]
- Component or Package Name: `jsx-email`
- Component or Package Version: 2.1.5
- `@jsxp-email/cli` Version?:
- Operating System (or Browser): MacOS., it doesn't matter
- Node Version: v20
- Link to reproduction _(⚠️ read below)_:

When you deploy a preview app onto a subpath such as `https://mydomain.com/emails/` it doesn't work. 
The links to assets in the `index.html` are absolute.

So when you open `https://mydomain.com/emails/` the index.html is loaded, but it tries to download assets from the root`/` instead of the subpath `/emails`

The assets link should be relative, or there should be a way to specify a `basePath` for the build. 

I don't know how to create a reproduction link for this, because to showcase it you need to basically deploy it somewhere. 

You can reproduce it locally by following the steps:

- `email preview ./emails/templates --build-path /tmp/subpath/email-preview`
- `npx http-server  /tmp/subpath/`
- Open link http://127.0.0.1:8080/email-preview/

The preview would be broken. 

Also, the need to provide an absolute path for the `--build-path` is counterintuitive, i spend half an hour to understand where it goes when you pass relative path like `--build-path ./dist/emails`

For us this is important, because im trying to deploy a preview from PRs to the github pages, and it is deployed to a subpath such as `https://owner.github.io/repo-name/pr-223/emails` and doesn't work when served from this PR.

**Comment by shellscape** [comment]
_(Note: No reproduction needed on this one since it was discussed in Discord prior)_

**Comment by timofei-iatsenko** [comment]
For reference: https://vite.dev/guide/build#public-base-path

Currently there is 

```js
    await viteBuild({
        ...config,
        base: '/',
       // ...
    });
```

I don't know is it possible to achieve it without explicit passing a `base` option as for vite cli

**Comment by timofei-iatsenko** [comment]
Tested it with patch settings the `base` property to my subpath. It still doesn't work, now because of the internal router issue

**Comment by shellscape** [comment]
I've got to take a look at how it's breaking. I'll have some time this afternoon to do that, have a lot of work work to take care of this morning.

**Comment by shellscape** [comment]
Thanks for all this info. This is next on my list to tackle.
