### ISSUE TITLE
Next.js build fails after upgrading from 2.1.5 to 2.2.0

### ISSUE THREAD

**Issue by EvHaus** [shellscape/jsx-email#248]
- Component or Package Name: `jsx-email`
- Component or Package Version: `2.2.0`
- `@jsxp-email/cli` Version?: Not used
- Operating System (or Browser): MacOS 15.1.1 (and reproduced on Vercel architecture too)
- Node Version: 20.16.0
- Link to reproduction: https://stackblitz.com/edit/jsx-email-bug?file=package.json,app%2Fpage.tsx,README.md

### Expected Behavior

Successful build when using `next build` command.

### Actual Behavior

The `next build` command fails with:

```
Failed to compile.

./node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.d.ts
Module parse failed: Unexpected token (1:7)
File was processed with these loaders:
 * ./node_modules/.pnpm/next@15.0.3_@babel+core@7.25.7_react-dom@19.0.0-rc-91061073-20241121_react@19.0.0-rc-91061073_a6r3revzxqaafyg3dsrzt5mdiy/node_modules/next/dist/build/webpack/loaders/next-flight-loader/index.js
 * ./node_modules/.pnpm/next@15.0.3_@babel+core@7.25.7_react-dom@19.0.0-rc-91061073-20241121_react@19.0.0-rc-91061073_a6r3revzxqaafyg3dsrzt5mdiy/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
You may need an additional loader to handle the result of these loaders.
> export type Platform = 'browser' | 'node' | 'neutral'
| export type Format = 'iife' | 'cjs' | 'esm'
| export type Loader = 'base64' | 'binary' | 'copy' | 'css' | 'dataurl' | 'default' | 'empty' | 'file' | 'js' | 'json' | 'jsx' | 'local-css' | 'text' | 'ts' | 'tsx'

Import trace for requested module:
./node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.d.ts
./node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/ sync ^.*\/.*$
./node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js
./node_modules/.pnpm/jsx-email@2.2.0_@jsx-email+app-preview@2.0.2_@types+node@22.9.3_@types+react-dom@18.3.1_@type_3l5myp3qqt6xe4dei6hjyx2ha4/node_modules/jsx-email/dist/esm/renderer/compile.js
./node_modules/.pnpm/jsx-email@2.2.0_@jsx-email+app-preview@2.0.2_@types+node@22.9.3_@types+react-dom@18.3.1_@type_3l5myp3qqt6xe4dei6hjyx2ha4/node_modules/jsx-email/dist/esm/index.js
./app/action-quote.tsx
```

### Additional Information

Rolling back to 2.1.5 makes the issue go away.

**Comment by shellscape** [comment]
You might have to change the next config to mark esbuild as external. Doesn't look like next is tree shaking that out.

**Comment by shellscape** [comment]
Hm. I forked your reproduction and ran `npm add jsx-email@2.2.0` and then ran `npm run dev` and it appears to have compiled without any problems. Here's the fork https://stackblitz.com/edit/jsx-email-bug-kxbegg?file=package.json,app%2Fpage.tsx,app%2Flayout.tsx

**Comment by EvHaus** [comment]
It's `pnpm run build` that fails. Starting the dev server works.

**Comment by shellscape** [comment]
This is what I get from `npm run build`:

```
~/projects/jsx-email-bug 10m 25s
❯ npm run build

> my-app@0.1.0 build
> next build

  ▲ Next.js 14.2.18

   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types  ...Failed to compile.

app/page.tsx
Type error: Page "app/page.tsx" does not match the required types of a Next.js Page.
  "action" is not a valid Page export field.
```

**Comment by shellscape** [comment]
Yeah it's been getting progressively worse since they went all AI-focused. I'm in touch with Replit about getting setup for repros.

**Comment by shellscape** [comment]
https://stackoverflow.com/questions/72229395/esbuild-in-nextjs-you-may-need-an-appropriate-loader-to-handle-this-file-type

Finding a lot of folks randomly running into this, haven't found a solution yet.

**Comment by shellscape** [comment]
OK it's definitely the export of `compile.js` in the published package. Nextjs is choking on `d.ts` files. This is _technically not our fault_ and nextjs is a minefield. I also had to add the following to the next.config.js file in the repro repo (say that 10 times fast) to get past another build error:

```
  webpack: (config) => {
    config.resolve.fallback = { fs: false };

    return config;
  },
```

The immediate fix on our end is to create a separate export path in package.json for the compile method, which is reasonable. But I'd also like to investigate a workaround because you're likely to run into that again down the road.

**Comment by shellscape** [comment]
I went down a rabbit hole trying to get this working with next, but it just gets deeper. Nextjs is a disease. 

```
pnpm add esbuild-loader react critters -D
```

```js
webpack: (config) => {
    config.externals = {
        'node:fs/promises': 'commonjs2 node:fs/promises',
    };

    config.module.rules.push({
      test: /\.tsx?$/,
      loader: 'esbuild-loader',
      options: {
        loader: 'tsx', // Or 'ts' if you don't need tsx
        target: 'es2015'
      }
    });

    config.resolve.fallback = {
      child_process: false,
      fs: false,
      'node:fs/promises': false
    };

    return config;
  }
```

**Comment by shellscape** [comment]
Alright this works, gets past the error (original suggestion, you just added it to the wrong externals):

```
    config.externals = {
        'node:fs/promises': 'commonjs2 node:fs/promises',
        esbuild: 'esbuild'
    };

    config.resolve.fallback = {
      child_process: false,
      fs: false,
      'node:fs/promises': false
    };
```

But the app itself seems to have other issues, since I run into a `TypeError: Cannot read properties of null (reading 'useContext')` error even after removing all of the jsx-email stuff.

**Comment by shellscape** [comment]
Alright the release was a little bumpy because of `tshy` but got a patch release up that gets around this problem. Hopefully that info ☝️ is useful for the next time you run into something like this.

**Comment by EvHaus** [comment]
Thanks. Latest version solved it for me.

Agree that Next.js configuration is a total disaster.
