### ISSUE TITLE
Unable to load jsx-email.config

### ISSUE THREAD

**Issue by dan-smt** [shellscape/jsx-email#257]
- Component or Package Name:
- Component or Package Version: 2.4.1
- `@jsxp-email/cli` Version?:
- Operating System (or Browser): MacOS
- Node Version: 20.10
- Link to reproduction _(⚠️ read below)_: https://github.com/dan-smt/jsx-email-reproduction/tree/main/render-function-unable-to-load-config

### Expected Behavior
console log html & plaintext

### Actual Behavior
Terminal error:
```
⨯ Error: Cannot find module '/Users/code/jsx-email-issues-reproduction/render-function-unable-to-load-config/jsx-email.config.mjs'
    at /Users/code/jsx-email-issues-reproduction/render-function-unable-to-load-config/.next/server/app/(app)/page.js:25:11
    at sendEmail (./src/app/(app)/actions.tsx:22:18)
```

### Additional Information

To test install dependencies then run `pnpm dev`, this will start nextjs, then click the only button on the top left of the screen

I've tracked the issue down to the `render` function specifically, interesting behaviour:

1. comment out `render`,
2. run code with `renderPlainText`
3. add back in `render`
4. it works

maybe it completely ignored the config here? not sure

**Comment by dan-smt** [comment]
For anyone reading: you can pass in the same render options you would put in the config as a second parameter on the `render` function, and it'll work the same way

**Comment by shellscape** [comment]
I think this one is good to go now that tailwind updated. next.js could still potentially be an issue in the future.
