### ISSUE TITLE
Preview doesn't consider changes to files outside the preview directory

### ISSUE THREAD

**Issue by osdiab** [shellscape/jsx-email#270]
- Component or Package Name: jsx-email
- Component or Package Version: 2.5.4
- `@jsxp-email/cli` Version?: whatever came with it
- Operating System (or Browser): Mac OSX
- Node Version: 22
- Link to reproduction _(⚠️ read below)_: https://github.com/osdiab/repro-jsx-email-watch-outside-templates

### Expected Behavior
- when changing the number in `other-code.ts`, HMR should kick in and recognize that the underlying code for the template changed

### Actual Behavior
- it will never update until you restart the preview server

### Additional Information
- Getting around this for now by using `chokidar-cli` to restart the server when changes elsewhere occur.

**Comment by osdiab** [comment]
also unrelated but I couldn't get neither the stackblitz nor code sandbox repro links to actually run the preview server without crashing.

**Comment by shellscape** [comment]
Thanks for the issue. This was covered in the discussion here: https://github.com/shellscape/jsx-email/discussions/268#discussioncomment-11607991

We'll be re-adding this feature after the holidays. (Closing because it was an intentional downgrade, ignore the "closed as completed").
