### ISSUE TITLE
Is Bun supported?

### ISSUE THREAD

**Issue by yannxaver** [shellscape/jsx-email#39]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The docs currently do not mention bun.
	
### Your Proposal for Changes

If it is supported, it could be added to all the examples.

**Comment by shellscape** [comment]
Not sure! I'm not a Bun or Deno user. Good bet if Bun supports React. 

We have a discord server and discussions for general Q & A, that's a better spot than issues. Feel free to open an issue with a reproduction with a filled-in template if something doesn't work right.

**Comment by shellscape** [comment]
Well that's what I get for viewing on mobile :) Sorry for the misstep.

**Comment by shellscape** [comment]
@Jarred-Sumner anyone on staff that could give this a spin with bun to answer OP's question of support?

**Comment by XMadFoX** [comment]
<details>
<summary>Well, looks so (vite and react are supported, so why not)</summary>

![image](https://github.com/shellscape/jsx-email/assets/37180406/3d264af5-553c-418e-85a1-3b06e439d65d)

</details>

**Comment by shellscape** [comment]
That's good news! We'll update the docs very soon. Thanks for taking a look at that

**Comment by XMadFoX** [comment]
I am not on bun staff BTW 😳
But just followed `try it and see`

You may want to wait for their response

**Comment by shellscape** [comment]
The try it and see is good enough for me. That screenshot shows me what I needed to know. 

side note: was it any faster?

**Comment by XMadFoX** [comment]
build ~2x faster
![image](https://github.com/shellscape/jsx-email/assets/37180406/bef1b84c-906f-4a33-a6e9-c5a17d1a5c7d)
![image](https://github.com/shellscape/jsx-email/assets/37180406/01139f9d-2fdb-44a5-8635-94cd9f5ef321)

**Comment by shellscape** [comment]
alright bun support was pushed and should be visible on the sight in a few minutes! thanks @XMadFoX
