### ISSUE TITLE
Unable to render in a next.js server action

### ISSUE THREAD

**Issue by yannxaver** [shellscape/jsx-email#40]
- Component or Package Name: @jsx-email/render
- Component or Package Version: 1.0.1
- `@jsxp-email/cli` Version?: 1.0.14
- Link to reproduction _(⚠️ read below)_: https://stackblitz.com/edit/stackblitz-starters-k14u31?file=app%2Faction.ts

### Expected Behavior

Should be able to render in a server action.

### Actual Behavior

```shell
You're importing a component that imports react-dom/server. To fix it, render or return the content directly as a Server Component instead for perf and security.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

The error was caused by importing '@jsx-email/render/dist/es/index.js' in './app/action.ts'.
```

### Additional Information

This is related to
https://github.com/resendlabs/react-email/issues/871
https://github.com/vercel/next.js/issues/43810 (probably includes the fix)

It has been fixed in react-email already because I was able to render in a server action using their package before.

**Comment by shellscape** [comment]
https://github.com/shellscape/jsx-email/pull/36 will resolve this.

**Comment by yannxaver** [comment]
Looks good. (https://stackblitz.com/edit/stackblitz-starters-f4gt7r?file=package.json)

So the solution for now would be to install all components individually and to not use the `all` package? 
When do you _roughly_ expect it to be updated? 

tbh, it was unexpected that the `all` package exports `render` as well. In the [docs](https://jsx.email/docs/components/all) it sounds like it just exports the components.

**Comment by shellscape** [comment]
thought about changing that too, but went with it as it is to make it easy for people to switch from react-render

**Comment by shellscape** [comment]
[all v2.1.0](https://github.com/shellscape/jsx-email/commit/55ac5668dee79ed4521499de8acbb35b2d7d9983) published

Please give this a test and let us know how it works out

**Comment by yannxaver** [comment]
No more error message (https://stackblitz.com/edit/stackblitz-starters-83gr6n?file=app%2Faction.ts)

The rendering output also looks good. 

Do you plan to publish releases [here](https://github.com/shellscape/jsx-email/releases) with change logs? I would subscribe to them.

**Comment by shellscape** [comment]
> Do you plan to publish releases here with change logs? I would subscribe to them.

possibly in the future, but for now we're just tagging and updating the changelog.
