### ISSUE TITLE
Does not build on windows

### ISSUE THREAD

**Issue by Yaro77** [shellscape/jsx-email#41]
- Component or Package Name: cli
- Component or Package Version: 1.1.0
- `@jsxp-email/cli` Version?: 1.1.0
- Operating System (or Browser): Windows 11
- Node Version: 18.14.2
- Link to reproduction _(⚠️ read below)_: Brand new project on Windows, created with `npm create jsx-email`, no need for reproduction.

### Expected Behavior

Build works on Windows

### Actual Behavior

It doesn't

### Additional Information

Can't create PR now
Build command uses `globby`, which returns empty arrays on windows paths. You should use `globby([slash(join(temp, "*.js")])` everywhere in CLI.
Thanks

**Comment by shellscape** [comment]
> no need for reproduction

Sorry, but that's not true. If you're not willing to help demonstrate the issue, I'm afraid there's nothing we can do to help.

None of the current maintainers are Windows users, so I'd recommend using WSL for the time being.

**Comment by bhuynhdev** [comment]
Hi, just want to let the team know that I am experience the same issue in Windows. The Development server works fine, but when I run `pnpm run build`, it says found 0 files, even though my templates folder contains one file "jsx-email-starter". This is for a brand new project just created using the cli (version `1.1.0`)
```bash
email build ./templates

Found 0 files:

Starting build...

Build complete. Files written to: ...
```

**Comment by shellscape** [comment]
A PR would be great. Appreciate the additional info. This issue is more than likely the result of the older version of globby that we're using at the moment. I still don't know what exact fix the OP was referencing, but it probably has to do with path normalization.

**Comment by bhuynhdev** [comment]
I dug around for a bit, and per this issue https://github.com/sindresorhus/globby/issues/179, I replaced `globby([glob])` with `globby([glob.replace(/\\/g, '/')])` in the `build` function and `globby([join(outDir, '*.js').replace(/\\/g, '/')])` in the `compile` function and the CLI now successfully detected the files. I did run "cannot find modules `react/jsx-runtime`" but solved it by running `pnpm add react`

I am trying to make a PR but the steps in the CONTRIBUTING.md doc seems to not work on my WSL. I have Nodejs 18.18.2, and have ran `pnpm boostrap`. But when I run ` moon run repo:build.packages`, I got error
```bash
Error: project_graph::unknown_project

  × No project has been configured with the name or alias jsx-email.
```

**Comment by shellscape** [comment]
Thanks for the heads up, I'll get the doc updated. In place of `jsx-email` use `repo` for moon commands.

**Comment by shellscape** [comment]
Also here's rollup's path normalization routine that's very proven, for reference https://github.com/rollup/plugins/blob/master/packages/pluginutils/src/normalizePath.ts#L5

**Comment by shellscape** [comment]
Attempted to setup a workflow matrix so we could use github actions to try and debug, but unfortunately there's an issue between `pnpm` and `vue-demi` that needs to be resolved before things will work correctly https://github.com/pnpm/pnpm/issues/6696#issuecomment-1784177984

**Comment by bhuynhdev** [comment]
Oh my bad. The issue is because I did not name my folder `jsx-email` (whereas Moon tried to decipher the project name from folder name). I am now using WSL (since the command `rm -rf` does not work on Windows), and ran into a new error after running `moon repo:build.packages`

```bash
src/tailwind.tsx(2,29): error TS2307: Cannot find module '@jsx-email/render' or its corresponding type declarations
```

**Comment by shellscape** [comment]
Thanks for working through that. We'll get that doc updated 👍
