### ISSUE TITLE
SVG not rendering correctly

### ISSUE THREAD

**Issue by mrtom** [shellscape/jsx-email#46]
- Component or Package Name: @jsx-email/all
- Component or Package Version: 2.2.2
- `@jsxp-email/cli` Version?: `@jsx-email/cli` (without the p, assuming that's a template typo?) v1.1.1
- Operating System (or Browser): MacOS, Chrome
- Node Version: 20.9.0
- Link to reproduction _(⚠️ read below)_:

StackBlitz link 404s unfortunately. There is a repo you can play with [here](https://github.com/mrtom/jsx-email-bug-report).

This repo contains the code created when you use the quick start in the JSX Email docs, with a single SVG JSX file added into the starter template.

### Expected Behavior

Here is what that SVG looks like when rendered in my Next app (first) and when sent using react-email (second)

<img width="1512" alt="Screenshot 2023-10-31 at 21 18 29" src="https://github.com/shellscape/jsx-email/assets/174462/44b8b7ee-6214-494a-9fa8-db57eedd6b06">

<img width="727" alt="Screenshot 2023-10-31 at 21 19 05" src="https://github.com/shellscape/jsx-email/assets/174462/545c16a2-27bf-4fb4-aded-7df97212fe63">

### Actual Behavior

Here is what the SVG looks like rendered by the JSX Email preview server (first) and an email generated by JSX Email (second)

<img width="1512" alt="Screenshot 2023-10-31 at 21 07 08" src="https://github.com/shellscape/jsx-email/assets/174462/52fc7d8f-e63e-44bd-bee3-a2d968a26488">

<img width="735" alt="Screenshot 2023-10-31 at 21 19 10" src="https://github.com/shellscape/jsx-email/assets/174462/845bd326-711a-48d6-ad16-d6e4e81cbe68">

Note the white 'tick' is missing in both cases.

**Comment by grahamplace** [comment]
I don't know the exact limitations, but as I'm starting to work with emails for the first time, my current stance is "we don't use SVG" to avoid confusion / issues 

https://css-tricks.com/a-guide-on-svg-support-in-email/

**Comment by shellscape** [comment]
SVG support is extremely dicey. See https://www.caniemail.com/features/image-svg/

That site is also awesome for viewing compatibility of features across clients.

**Comment by mrtom** [comment]
Wow, I had no idea it would be so poor in 2023. OK, time to use PNGs in emails! Thanks.
