### ISSUE TITLE
`build` throws in the starter

### ISSUE THREAD

**Issue by corysimmons** [shellscape/jsx-email#48]
`npm create jsx-email && cd jsx-email-starter && pnpm install && pnpm run build` throws:

```sh
> email build ./templates

Found 1 files:
   templates/jsx-email-starter.tsx

Starting build...
✘ [ERROR] Could not resolve "react/jsx-runtime"

    templates/jsx-email-starter.tsx:77:4:
      77 │     <Head />
         ╵     ^

  You can mark the path "react/jsx-runtime" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.
```

**Comment by shellscape** [comment]
thanks for the issue. in the future, please use the issue template. we're sticklers for that. 

run `npm add react -D` and you should be set. I'll update the create package now.

**Comment by shellscape** [comment]
fixed in https://github.com/shellscape/jsx-email/commit/b9a1373dd5c03628d28220d1ea0dacc1f615e7a1 

and `create-jsx-email@0.1.1` is on the registry.
