### ISSUE TITLE
Option to use preview with a nested template structure

### ISSUE THREAD

**Issue by co-sic** [shellscape/jsx-email#53]
- Component or Package Name: @jsx-email/cli
- Component or Package Version: 1.1.1

### Feature Use Case
I would like to group my email templates in different folder inside my root template folder but still be able to see them all in the preview tool. Currently you can only see the templates that are directly in the folder you specify and not in any subfolders.

### Feature Proposal
This could maybe be an additional option you can pass to also include all the folders inside your rooth path in the preview and then display the same folder structure on the nav bar on the left side.

**Comment by shellscape** [comment]
Totally. The single-level directory was always intended to be a temporary limitation.

**Comment by ibnumusyaffa** [comment]
+1 its very useful if you are grouping code by features, i hope its support path pattern like `./features/**/*.tsx`

```
features
├── products
│   └── templates
│       └── marketing.tsx
├── projects
│   └── templates
│       └── reminder.tsx
└── users
    └── templates
        └── forgot-password.tsx

```

**Comment by shellscape** [comment]
good news: @ryanlanciaux has stepped up to work on this.

**Comment by shellscape** [comment]
This is available in the latest `@jsx-email/app-preview` version and can be seen on https://samples.jsx.email
