### ISSUE TITLE
Infer TemplateProps & optinal props

### ISSUE THREAD

**Issue by sysmat** [shellscape/jsx-email#63]
- Component or Package Name: superstruct
- Component or Package Version: 1.0.3

Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

- when using superstruct & defaulted & infer  props of components become mandatory, so the idea of defaulted is misleading or even useless

```typescript
import { defaulted, number, object, string, type Infer } from 'superstruct';
export const TemplateStruct = object({
  email: defaulted(string(), 'batman@example.com'),
  name: defaulted(string(), 'Bruce Wayne')
});


export type TemplateProps = Infer<typeof TemplateStruct>;
export const Template = ({ email, name }: TemplateProps) => (
}
```
- so the usage Template  in another component or ts is mandatory

```typescript
import { Template as  BatmanTemplate} from './emails/BatmanEmail';

const html = render(<BatmanTemplate email="Bruce" name="Wayne" />);
```

### Your Proposal for Changes

- maybe function component with default values for its properties like in React
- or in batman example how to do it

**Comment by shellscape** [comment]
Sorry, not following you on this one.

**Comment by shellscape** [comment]
Closing this one as abandoned. Please ping if you'd like it reopened. For anyone who runs across this issue, `superstruct` has an `optional` that can be wrapped around any optional properties on props.

**Comment by sysmat** [comment]
`const html = render(<BatmanTemplate email="Bruce"  />);`  then name should be 'Bruce Wayne' but is not

**Comment by shellscape** [comment]
@sysmat would you like to put together a reproduction? I'm afraid I'm still not understanding you.

https://stackblitz.com/fork/jsx-email-repro

**Comment by sysmat** [comment]
- object from 'superstruct' and defaulted is total nonsense, not connected with jsx-email
- prop can not bi optional if using defaulted, so even if I use empty prop defaulted is not used
- in which case prop will be defaulted
