### ISSUE TITLE
send mail

### ISSUE THREAD

**Issue by sysmat** [shellscape/jsx-email#64]
- Component or Package Name: create-jsx-email
- Component or Package Version: 0.1.1

Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...

- there is some documentation in https://jsx.email/docs/email-providers
- but it is missing how to actually send it

### Your Proposal for Changes

- when using `create-jsx-email` create example sendMail.tsx
- when I create in root of project SendMail.tsx

```typescript
import { render } from '@jsx-email/render';
import nodemailer from 'nodemailer';
import React from 'react';

import { Template as  BatmanTemplate} from './emails/BatmanEmail';

const html = render(<BatmanTemplate email="Bruce" name="Wayne" />);
const transport = nodemailer.createTransport({
  host: xxx,
  port: xxx,
...
});

await transport.sendMail({
  from: xxx,
  to: xxxx,
  subject: 'jsx-email-starter',
  html: html
}); 
```
- then I need to install tsx and change project to `"type": "module"`,  `script : {"mail": "tsx SendMail.tsx"}` to be able to run `npm run mail`
- if any better solution it would be great

**Comment by shellscape** [comment]
You'd only need `module` if you're using top level await. You can wrap the call to nodemailer in an iife, or function that's called.

jsx-email is an email rendering package. much like react-email, you have to understand how to use a third party email provider along with the package.

**Comment by sysmat** [comment]
@shellscape thx, yes I could avoid "type": "module", by wrapping it in function
