### ISSUE TITLE
allow email preview to open in a different browser than Chrome by default, or just print a url

### ISSUE THREAD

**Issue by osdiab** [shellscape/jsx-email#65]
- Component or Package Name: `@jsx-email/cli`
- Component or Package Version: `2.0.0`

### Expected Behavior / Situation
I dont use Chrome as my main browser. When I run `pnpm exec email preview` I want it to either just print the URL, or open my actual default browser

### Actual Behavior / Situation
It opens Chrome every time

### Modification Proposal
- add a flag to make it not auto-open a browser, just print the localhost URL
- show that in the `--help` output

**Comment by osdiab** [comment]
oh, looks like it already has this:

https://github.com/shellscape/jsx-email/blob/dbeb481d28b3f5d107f82e61a982a43a10aa0f89/packages/cli/src/commands/preview.ts#L29

just it doesn't show in the help text.

**Comment by shellscape** [comment]
When you say that it doesnt show in the help text, what did you mean? On the console/terminal?

**Comment by osdiab** [comment]
what i mean is that i expected the `--help` terminal flag to show help text for a command, like `email preview --help` would show help text for the `preview` command, but it doesn't; it just gets ignored. 

if you want to see help text you need to use `email help preview`. so it's just that the CLI doesn't behave like other CLI tools I use.

**Comment by shellscape** [comment]
it's a very common pattern. So common that I'd bet you use a CLI everyday that uses the same pattern ;) https://git-scm.com/docs/git-help

The CLI docs https://jsx.email/docs/core/cli also show the `email help` command

**Comment by osdiab** [comment]
@shellscape but `git commit --help` does show you help about the `commit` command.

`email preview --help` shows you nothing helpful about the `preview` command.

**Comment by osdiab** [comment]
anyway, yeah, not a big deal but just saying that i didn't find that intuitive.
