### ISSUE TITLE
remove target from Button/Link

### ISSUE THREAD

**Issue by T04435** [shellscape/jsx-email#81]
- Component or Package Name: Button / Link
- Component or Package Version: 1.0.4 / 1.0.2

### Expected Behavior / Situation
According to https://www.caniemail.com/features/html-target/ target attribute is not supported and forced to "_blank", s it's recommended not to add it.

```
<a href="#" data-id="@jsx-email/button">Link</a>
```

### Actual Behavior / Situation
```
<a href="#" data-id="@jsx-email/button" target="_blank">Link</a>
```

### Modification Proposal
Remove target from button thinking it also applies to Link component

```
<a href="#" data-id="@jsx-email/button" target="_blank">OLD</a>
<a href="#" data-id="@jsx-email/button">NEW</a>
```

**Comment by lordelogos** [comment]
Hi @T04435, 

Thank you for pointing this out.
Would you be interested in submitting a pull request to implement this proposal?
