### ISSUE TITLE
Is this an inspiration?

### ISSUE THREAD

**Issue by Theryston** [shellscape/jsx-email#86]
I could see that jsx email is really similar to my JSX Mail, a tool that I'm working on in version 2 now, is this an inspiration (since my project is a little older) or is it just a coincidence?

I really liked the idea!

look at mine:

https://github.com/Theryston/jsx-mail

**Comment by shellscape** [comment]
Hey there! `jsx-email` started out as a fork of `react-email`. We've got a section on the README.md dedicated to attribution with some info on where the project comes from and why: https://github.com/shellscape/jsx-email#attribution-

From looking at your repo, I would bet that `react-email` used your project as a reference when building out theirs. We're a bit further along than your project at the moment; if you'd like to join in contributing here, you'd be more than welcome!

**Comment by Theryston** [comment]
Thank you! I really liked your project!
