### ISSUE TITLE
Hot reloading only working in Template pages

### ISSUE THREAD

**Issue by aidan-rypens** [shellscape/jsx-email#87]
Hot reloading for both JSX and JSS seems to work fine if you are editing a template page.

However, if you have - for example - building blocks outside of the 'template' context (as example: a `utils` folder with `Footer` or `ContentBlock`) changes will not trigger a reload. This console indicates: `[vite] hmr update` instead of `[vite] page reload`.

If I'm missing something, let me know. I couldn't find samples with this structure. At least in my opinion - could be wrong - it would be nice to have some reusable generic blocks with prefilled content & styling so only the basics are in your email templates.

Workaround
Create a template so it behaves like an email template but also export other stuff that can be reused over emails.

![image](https://github.com/shellscape/jsx-email/assets/19323152/0423aa91-f471-481b-aa2f-fc3fef1fd30a)

**Comment by shellscape** [comment]
Hey thanks for checking this out. I use the project daily for work and haven't had this issue. Please follow the instructions in the issue template for a reproduction and I'll be happy to take a look. It's probably an edge case with your setup, but I won't be able to tell without a reproduction.

**Comment by shellscape** [comment]
@aidan-rypens just checking in on this one

**Comment by lordelogos** [comment]
Hey @aidan-rypens, I am closing this now.

If the issue persists, kindly reopen and provide a reproduction using our StackBlitz template:
https://stackblitz.com/fork/jsx-email-repro

**Comment by dominictobias-bullish** [comment]
Hot reload doesn't work at all, the page does a hard reload. How did you get it to work at all? 🤯

I have 

```ts
export function Template() {
...
}
```

in my templates files
