### ISSUE TITLE
Unable to preview email templates

### ISSUE THREAD

**Issue by roguesherlock** [shellscape/jsx-email#90]
- Component or Package Name:
- Component or Package Version:
- `@jsxp-email/cli` Version?:
- Operating System (or Browser):
- Node Version:
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior
being able to view template

### Actual Behavior
unable to view template

### New Project
I just created a sample project with `create jsx-email` utility but I'm unable to preview the templates.

<img width="1512" alt="image" src="https://github.com/shellscape/jsx-email/assets/5683543/551b5d18-da46-4d36-b60e-c46385ddb3ca">

### Existing Project
And I get a different error If I add jsx email to an existing nextjs project 

<img width="1511" alt="image" src="https://github.com/shellscape/jsx-email/assets/5683543/7021aead-7c02-47bd-bf31-9caf5795a461">

**Comment by shellscape** [comment]
thanks for the issue. would be happy to help you, but please follow the instructions in the issue template and create a reproduction

**Comment by shellscape** [comment]
thanks, that might be a docs failure there. will have a fix for you today, in a few hours when my kids take a nap.

**Comment by shellscape** [comment]
transient dependency started resolving differently for some reason. working on a fix.

**Comment by shellscape** [comment]
@roguesherlock confirmed jsx-email@1.1.1 fixes the issue for your reproduction. please let us know if you run into anything else.
