### ISSUE TITLE
Cannot build template after creating it

### ISSUE THREAD

**Issue by aidan-rypens** [shellscape/jsx-email#92]
To reproduce:
1. Run `npx email create BatmanEmail`
2. Run `npx email build ./BatmanEmail.tsx`

Error:
![image](https://github.com/shellscape/jsx-email/assets/19323152/ac56ecaa-f817-4513-9649-4c0dff3b0c79)

Rendering the component out & emailing runs fine. However, because the layout received in the mailbox does not match the one from the preview and therefore wanted to debug a bit.

![image](https://github.com/shellscape/jsx-email/assets/19323152/ee4f8b4c-20f6-4264-a6b1-a5f0a9876240)

**Comment by shellscape** [comment]
Would love to help you out, but please first follow the instructions and create a reproduction using one of the options listed in the issue template.

**Comment by aidan-rypens** [comment]
Sure, I ran the following:
`npm create jsx-email`.

This starter project doesn't build nor can it run the check.

**Comment by shellscape** [comment]
Not trying to be difficult here, we just ask everyone (even maintainers) to follow the same instructions. The template has the following content right before inputs:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the StackBlitz reproduction template at https://stackblitz.com/fork/jsx-email-repro
>   2. Provide a minimal repository link (Read https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

I worked on the `create-jsx-email` package just a day or so ago and tested it working and just ran it again and it's working fine here. So unless you can provide an actual repro with code I can look at, there's really nothing I can do for you to help

**Comment by shellscape** [comment]
Tweaked the exports inspection logic in any event. Maybe jsx-email@1.1.2 will work for your case.

**Comment by aidan-rypens** [comment]
@shellscape I understand, here is the stackblitz url:

https://stackblitz.com/edit/jsx-email-repro-wjaq7f?file=templates%2FReproduction.tsx

![image](https://github.com/shellscape/jsx-email/assets/19323152/1f0600a2-382f-478e-823c-7ac0676279ed)

**Comment by shellscape** [comment]
Here's my fork off of yours: https://stackblitz.com/edit/jsx-email-repro-9j4pkr?file=package.json

I updated to 1.1.2 and ran `pnpm i` to make sure the newest version was installed, and then ran `pnpm build`. It successfully built:

<img width="685" alt="Screenshot 2023-12-05 at 12 29 05 PM" src="https://github.com/shellscape/jsx-email/assets/76371/46767152-ef87-4612-89f6-398980aa24d9">

**Comment by shellscape** [comment]
Also for what it was worth, without forking yours, I was able to update jsx-email and run build. This screenshot is from your stackblitz:

<img width="622" alt="Screenshot 2023-12-05 at 12 31 19 PM" src="https://github.com/shellscape/jsx-email/assets/76371/39a49e53-f3fc-4017-8fee-92ccf2a9a731">

**Comment by aidan-rypens** [comment]
@shellscape By adding `import * as React from "react";` it does indeed work.

Not sure why it was not added though, because I generated with the CLI as an example. The CLI create command does generate a sample with the import. I may have removed the line by accident, weird.

Thanks for having a look!

**Comment by shellscape** [comment]
No wories! Glad it worked out
