### ISSUE TITLE
Preview for mobile

### ISSUE THREAD

**Issue by wladpaiva** [shellscape/jsx-email#99]
- Component or Package Name: jsx-email
- Component or Package Version: latest

### Feature Use Case
react-email is got the preview mobile which is pretty cool to have an idea of how the email will look like in both devices

### Feature Proposal
I personally find the switch a bit annoying so since most of emails is 640px wide max, I'd just show simultaneously the mobile and desktop on the same screen. I'd same some time.

**Comment by shellscape** [comment]
For sure! We've got an active branch for this here: https://github.com/shellscape/jsx-email/tree/feat/jsx-email/preview-devices. You're welcome to checkout that branch and give it a shot. It's not quite where I want it to be, but it's close. And as per usual it's a far better experience than what `react-email` have cobbled together 🙊  I'm hoping to get this done early next week.

I posted a preview on discord last week as well https://discord.com/channels/1156307748552716398/1156766131462361211/1183525703069732966

![](https://cdn.discordapp.com/attachments/1156766131462361211/1183525702855819264/Screenshot_2023-12-10_at_4.48.06_PM.png?ex=6588a734&is=65763234&hm=684d432d2e668aa1ac3bd4d93066dbe0b43eda581571d65fc16783a12793607e&)
